### ISSUE TITLE
predictor files look weird

### ISSUE THREAD

**Issue by maxbiostat** [djmagee5/BEAST_GLM#3]
even github is complaining of unequal numbers of lines.

Why is that?

**Comment by djmagee5** [comment]
Can you be a little more specific? Is it your predictor input file or the "predictorNames" output file? Attaching your XML and predictor file(s) would be great.

**Comment by maxbiostat** [comment]
The example predictor files look a bit weird. Github's automatic CSV parser says "It looks like row 2 should actually have 22 columns, instead of 23."

So maybe there's one extra column that shouldn't be there?

**Comment by djmagee5** [comment]
Apparently so. Must've done an off-by-one loop when I made those up. I removed the extra column from each.

**Comment by maxbiostat** [comment]
Brilliant. Closing this.
